package BanqueCorba;


/**
* BanqueCorba/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Saturday, October 28, 2017 6:54:36 PM WEST
*/

public interface IBanqueRemoteOperations 
{
  double conversion (double montant);
  BanqueCorba.Compte getCompte (int code);
  BanqueCorba.Compte[] getComptes ();
} // interface IBanqueRemoteOperations
